spring.application.name=sunat-consulta
server.port=8081

# H2 Database
spring.datasource.url=jdbc:h2:mem:sunatdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Decolecta API
decolecta.api.url=https://api.decolecta.com
decolecta.token=sk_4189.bVz8NjiLh67E1htxgqyNxKbibyPoWMe0
